language: shell
script:
    - chmod o+x ./scripts/make_dist.sh
    - /usr/bin/env  ./scripts/make_dist.sh
deploy:
    provider: releases
    api_key:
        secure: "UmJ+VIBf3PewipcT/i+qfK1XUq+ge54lWs87XJqd0nbtc4B0diK0LOx/I6Qlu4EusGTtIZv3w5eYzjGRvbJ+1YaZFnKXfsXn4vopuMs0j0UqL5/Csu/f1mMBReMx6+EhCtmLND2f9jtnEB5WLmqiVpuvJjQmWUu2sBipHAof/DJlY7/ZzRDrTVDHNJp2PMzWQ1GfgbLhlP2yai3GhHxFMzbxQp3oc83+n3j/d9y03wUmDSNbBfIhB4WbgGjaGBXuOx5Am1I4hgGqz7hV+5V2uEh8ZvASVDP+GkjK5f6FBiHe92lISytnzThkNq1JKv39MaTDQzKDtNCQHpjFdEUQ+6l1+pgJH73l6btYMaXtFOywcJ64LYGFdvkx/gkoPzUZCOZO97NvQxK18iJAaw0hVrNbFtWqdPO/MhltdU9z/gA3Huqm8QDFcQHTPtfnzEqK3MiaOQoSnC0H7pvJdH6ZqBwn01bJxMdIf2e1YW6SeCaVZjQSBPZVZ5vMAjhQ7uYA/PpW2le/oSvo5XsgMoON27Jy1raapYlJnn9aP5xj69N36L/QPM7VOP6D/tQyIIQUEIT4b3IH/wya6lIsRbcFP7hpE6895bi+43qCnwee7T9w+UwNZC4N1rZ70Lp5oZSo47FHzae160rmIhyvFrTTK6NA3t6oAhL/xj5u3nfjuYU="
    file: dist/*.zip
    file_glob: true
    skip_cleanup: true
    on:
        repo: fortinet/fortiweb-ha
        tags: true
        branch: master


